plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'cu.lazaroysr96'
version = '1.0.0'

repositories {
    mavenCentral()
}

javafx {
    version = '21.0.5'
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

dependencies {
    implementation 'org.xerial:sqlite-jdbc:3.47.1.0'
    implementation 'com.google.code.gson:gson:2.11.0'
}

application {
    mainClass = 'cu.lazaroysr96.gci.MainApp'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named('jar') {
    manifest {
        attributes 'Main-Class': 'cu.lazaroysr96.gci.MainApp'
    }
}